#!/bin/sh

# simple openconnect wrapper

if [ $# -ne 2 ]
then
  echo "missing arg"
  usage
fi

CUSTOMER=$1
cmd=$2

CMD_OPTS=
CUSTOMERCONF=~/.vpn/${CUSTOMER}.conf
PIDFILE=/run/openconnect.pid
[ -f $PIDFILE ] && PID=$(cat $PIDFILE)

usage()
{
  echo "USAGE: sudo vpn <customer> up|down"
  exit 1
}
vpn_up()
{

  if [ -f $CUSTOMERCONF ]
  then
    while read line
    do
      CMD_OPTS="$CMD_OPTS $line"
      # echo $CMD_OPTS
    done < $CUSTOMERCONF
  else
    echo "$CUSTOMERCONF not found!"
    exit 1
  fi

  # PID=$(pidof openconnect)
  if [ ! -f $PIDFILE ]
  then
    sudo openconnect --background --pid-file=$PIDFILE $CMD_OPTS
  else
    echo "openconnect process $PID already running."
  fi

  # exit 0
}

vpn_down()
{
  if [ -f "$PIDFILE" ]; then
    sudo kill $PID
  else
    echo "openconnect process not running."
  fi
  exit 0
}

case $cmd in
  up)
    vpn_up;;
  down)
    vpn_down;;
  *)
  usage
  ;;
esac
